#!/bin/sh

for P in F D; do
  O=`echo $P |tr 'FD' 'DF'`
  p=`echo $P |tr 'A-Z' 'a-z'`
  o=`echo $O |tr 'A-Z' 'a-z'`

  ./makespecific qop_p.h $P "" >qop_$p.h
  ./makespecific qop_p_internal.h $P "" >qop_${p}_internal.h

  ./makegeneric qop_p.h P $P >qop_${p}_generic.h
  ./makegeneric qop_p_internal.h IP $P >qop_${p}_internal_generic.h

  for C in 1 2 3 N; do
    c=`echo $C |tr 'A-Z' 'a-z'`

    #./makespecific qop_pc.h $P$C >qop_$p$c.h
    #./makespecific qop_pc_internal.h $P$C >qop_$p${c}_internal.h

    ./makespecific qop_pc.h $P $C >qop_$p$c.h
    ./makespecific qop_pc_internal.h $P $C >qop_$p${c}_internal.h

    #./makegeneric qop_pc.h P $P >qop_$p${c}_generic.h
    ./makegeneric qop_pc.h PC $P$C >qop_$p${c}_generic.h
    ./makegeneric qop_pc.h PC $P$C $P >qop_$p${c}_color_generic.h
    ./makegeneric qop_pc.h PC $P$C $C >qop_$p${c}_precision_generic.h
    ./makegeneric qop_pc_internal.h IPC $P$C >qop_$p${c}_internal_generic.h
  done
done

for C in 1 2 3 N; do
  c=`echo $C |tr 'A-Z' 'a-z'`
  #./makespecific qop_poc.h F$C >qop_df$c.h
  #./makespecific qop_poc.h D$C >>qop_df$c.h
  ./makespecific qop_poc.h F $C >qop_df$c.h
  ./makespecific qop_poc.h D $C >>qop_df$c.h
  ./makegeneric qop_pc.h C $C >qop_df${c}_color_generic.h
  ./makegeneric qop_poc.h POC FD$C FD >>qop_df${c}_color_generic.h
  ./makegeneric qop_poc.h POC DF$C DF >>qop_df${c}_color_generic.h
done
