// DO NOT EDIT
// generated from qop_pc_internal.h
#ifndef _QOP_FN__IPC_GENERIC_H
#define _QOP_FN__IPC_GENERIC_H

#define QOP_asqtad_create_L_from_L QOP_FN_asqtad_create_L_from_L
#define QOP_asqtad_create_L_from_r_times_L QOP_FN_asqtad_create_L_from_r_times_L
#define QOP_asqtad_deriv_multi_fnmat_qdp QOP_FN_asqtad_deriv_multi_fnmat_qdp
#define QOP_asqtad_dslash_get_tmp QOP_FN_asqtad_dslash_get_tmp
#define QOP_asqtad_force_multi_asvec_qdp QOP_FN_asqtad_force_multi_asvec_qdp
#define QOP_asqtad_force_multi_fnmat_qdp QOP_FN_asqtad_force_multi_fnmat_qdp
#define QOP_asqtad_L_peq_L QOP_FN_asqtad_L_peq_L
#define QOP_ColorVector_struct QOP_FN_ColorVector_struct
#define QOP_DiracFermion_struct QOP_FN_DiracFermion_struct
#define QOP_dw_EO_project QOP_FN_dw_EO_project
#define QOP_dw_EO_reconstruct QOP_FN_dw_EO_reconstruct
#define QOP_dw_schur2_qdp QOP_FN_dw_schur2_qdp
#define QOP_dw_schur_qdp QOP_FN_dw_schur_qdp
#define QOP_eigcg_t_D QOP_FN_eigcg_t_D
#define QOP_eigcg_t_V QOP_FN_eigcg_t_V
#define QOP_FermionLinksAsqtad_struct QOP_FN_FermionLinksAsqtad_struct
#define QOP_FermionLinksDW_struct QOP_FN_FermionLinksDW_struct
#define QOP_FermionLinksHisq_struct QOP_FN_FermionLinksHisq_struct
#define QOP_FermionLinksWilson_struct QOP_FN_FermionLinksWilson_struct
#define QOP_Force_struct QOP_FN_Force_struct
#define QOP_gauge_deriv QOP_FN_gauge_deriv
#define QOP_GaugeField_struct QOP_FN_GaugeField_struct
#define QOP_gauge_scale QOP_FN_gauge_scale
#define QOP_get_mid QOP_FN_get_mid
#define QOP_hisq_deriv_multi_fnmat2_qdp QOP_FN_hisq_deriv_multi_fnmat2_qdp
#define QOP_hisq_force_multi_fnmat2_qdp QOP_FN_hisq_force_multi_fnmat2_qdp
#define QOP_hisq_force_multi_wrapper_fnmat QOP_FN_hisq_force_multi_wrapper_fnmat
#define QOP_invert_bicgstab_D QOP_FN_invert_bicgstab_D
#define QOP_invert_cg_D QOP_FN_invert_cg_D
#define QOP_invert_cgms_D QOP_FN_invert_cgms_D
#define QOP_invert_cgms_vD QOP_FN_invert_cgms_vD
#define QOP_invert_cgms_V QOP_FN_invert_cgms_V
#define QOP_invert_cg_vD QOP_FN_invert_cg_vD
#define QOP_invert_cg_V QOP_FN_invert_cg_V
#define QOP_invert_eigcg_D QOP_FN_invert_eigcg_D
#define QOP_invert_eigcg_V QOP_FN_invert_eigcg_V
#define QOP_invert_gcr2_D QOP_FN_invert_gcr2_D
#define QOP_invert_gmres2_D QOP_FN_invert_gmres2_D
#define QOP_linop_t_D QOP_FN_linop_t_D
#define QOP_linop_t_vD QOP_FN_linop_t_vD
#define QOP_linop_t_V QOP_FN_linop_t_V
#define QOP_qdpM_eq_raw QOP_FN_qdpM_eq_raw
#define QOP_relnorm2_D QOP_FN_relnorm2_D
#define QOP_relnorm2_V QOP_FN_relnorm2_V
#define QOP_wilson_dslash_get_tmp QOP_FN_wilson_dslash_get_tmp
#define QOP_wilson_initialize_gauge_L QOP_FN_wilson_initialize_gauge_L

#endif // _QOP_FN__IPC_GENERIC_H
