// DO NOT EDIT
// generated from qop_pc.h
#ifndef _QOP_DN__PC_GENERIC_H
#define _QOP_DN__PC_GENERIC_H

#define QOP_asqtad_convert_L_from_qdp QOP_DN_asqtad_convert_L_from_qdp
#define QOP_asqtad_convert_L_from_raw(...) QOP_DN_asqtad_convert_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_asqtad_convert_L_to_qdp QOP_DN_asqtad_convert_L_to_qdp
#define QOP_asqtad_convert_L_to_raw QOP_DN_asqtad_convert_L_to_raw
#define QOP_asqtad_create_L_from_G2 QOP_DN_asqtad_create_L_from_G2
#define QOP_asqtad_create_L_from_G QOP_DN_asqtad_create_L_from_G
#define QOP_asqtad_create_L_from_qdp QOP_DN_asqtad_create_L_from_qdp
#define QOP_asqtad_create_L_from_raw(...) QOP_DN_asqtad_create_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_asqtad_ddagd_norm2 QOP_DN_asqtad_ddagd_norm2
#define QOP_asqtad_ddagd QOP_DN_asqtad_ddagd
#define QOP_asqtad_deriv_multi_qdp QOP_DN_asqtad_deriv_multi_qdp
#define QOP_asqtad_deriv QOP_DN_asqtad_deriv
#define QOP_asqtad_destroy_L QOP_DN_asqtad_destroy_L
#define QOP_asqtad_diaginv_qdp QOP_DN_asqtad_diaginv_qdp
#define QOP_asqtad_diaginv QOP_DN_asqtad_diaginv
#define QOP_asqtad_dslash_dir_qdp QOP_DN_asqtad_dslash_dir_qdp
#define QOP_asqtad_dslash_dir QOP_DN_asqtad_dslash_dir
#define QOP_asqtad_dslash_qdp QOP_DN_asqtad_dslash_qdp
#define QOP_asqtad_dslash QOP_DN_asqtad_dslash
#define QOP_asqtad_extract_L_to_qdp QOP_DN_asqtad_extract_L_to_qdp
#define QOP_asqtad_extract_L_to_raw QOP_DN_asqtad_extract_L_to_raw
#define QOP_asqtad_force_multi_qdp QOP_DN_asqtad_force_multi_qdp
#define QOP_asqtad_force_multi QOP_DN_asqtad_force_multi
#define QOP_asqtad_force QOP_DN_asqtad_force
#define QOP_asqtad_get_eigcg QOP_DN_asqtad_get_eigcg
#define QOP_asqtad_invert_multi_qdp QOP_DN_asqtad_invert_multi_qdp
#define QOP_asqtad_invert_multi QOP_DN_asqtad_invert_multi
#define QOP_asqtad_invert_qdp QOP_DN_asqtad_invert_qdp
#define QOP_asqtad_invert QOP_DN_asqtad_invert
#define QOP_asqtad_invert_threaded_qdp QOP_DN_asqtad_invert_threaded_qdp
#define QOP_asqtad_invert_threaded QOP_DN_asqtad_invert_threaded
#define QOP_asqtad_load_L_from_G2 QOP_DN_asqtad_load_L_from_G2
#define QOP_asqtad_load_L_from_G QOP_DN_asqtad_load_L_from_G
#define QOP_asqtad_load_L_from_qdp QOP_DN_asqtad_load_L_from_qdp
#define QOP_asqtad_load_L_from_raw QOP_DN_asqtad_load_L_from_raw
#define QOP_asqtad_rephase_field_L_qdp QOP_DN_asqtad_rephase_field_L_qdp
#define QOP_asqtad_rephase_L QOP_DN_asqtad_rephase_L
#define QOP_asqtad_solve_multi_qdp QOP_DN_asqtad_solve_multi_qdp
#define QOP_ColorVector QOP_DN_ColorVector
#define QOP_convert_D_from_qdp QOP_DN_convert_D_from_qdp
#define QOP_convert_D_from_raw(...) QOP_DN_convert_D_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_convert_D_to_qdp QOP_DN_convert_D_to_qdp
#define QOP_convert_D_to_raw QOP_DN_convert_D_to_raw
#define QOP_convert_F_from_qdp QOP_DN_convert_F_from_qdp
#define QOP_convert_F_from_raw(...) QOP_DN_convert_F_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_convert_F_to_qdp QOP_DN_convert_F_to_qdp
#define QOP_convert_F_to_raw QOP_DN_convert_F_to_raw
#define QOP_convert_G_from_qdp QOP_DN_convert_G_from_qdp
#define QOP_convert_G_from_raw(...) QOP_DN_convert_G_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_convert_G_to_qdp QOP_DN_convert_G_to_qdp
#define QOP_convert_G_to_raw QOP_DN_convert_G_to_raw
#define QOP_convert_V_from_qdp QOP_DN_convert_V_from_qdp
#define QOP_convert_V_from_raw(...) QOP_DN_convert_V_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_convert_V_to_qdp QOP_DN_convert_V_to_qdp
#define QOP_convert_V_to_raw QOP_DN_convert_V_to_raw
#define QOP_create_D_from_qdp QOP_DN_create_D_from_qdp
#define QOP_create_D_from_raw(...) QOP_DN_create_D_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_create_F_from_qdp QOP_DN_create_F_from_qdp
#define QOP_create_F_from_raw(...) QOP_DN_create_F_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_create_G_from_qdp QOP_DN_create_G_from_qdp
#define QOP_create_G_from_raw(...) QOP_DN_create_G_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_create_V_from_qdp QOP_DN_create_V_from_qdp
#define QOP_create_V_from_raw(...) QOP_DN_create_V_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_destroy_D QOP_DN_destroy_D
#define QOP_destroy_F QOP_DN_destroy_F
#define QOP_destroy_G QOP_DN_destroy_G
#define QOP_destroy_V QOP_DN_destroy_V
#define QOP_DiracFermion QOP_DN_DiracFermion
#define QOP_dw_convert_L_from_G QOP_DN_dw_convert_L_from_G
#define QOP_dw_convert_L_from_qdp QOP_DN_dw_convert_L_from_qdp
#define QOP_dw_convert_L_from_raw(...) QOP_DN_dw_convert_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_dw_convert_L_to_G QOP_DN_dw_convert_L_to_G
#define QOP_dw_convert_L_to_qdp QOP_DN_dw_convert_L_to_qdp
#define QOP_dw_convert_L_to_raw QOP_DN_dw_convert_L_to_raw
#define QOP_dw_create_L_from_G QOP_DN_dw_create_L_from_G
#define QOP_dw_create_L_from_qdp QOP_DN_dw_create_L_from_qdp
#define QOP_dw_create_L_from_raw(...) QOP_DN_dw_create_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_dw_destroy_L QOP_DN_dw_destroy_L
#define QOP_dw_diaginv_qdp QOP_DN_dw_diaginv_qdp
#define QOP_dw_dslash2_qdp QOP_DN_dw_dslash2_qdp
#define QOP_dw_dslash2 QOP_DN_dw_dslash2
#define QOP_dw_dslash_qdp QOP_DN_dw_dslash_qdp
#define QOP_dw_dslash QOP_DN_dw_dslash
#define QOP_dw_extract_L_to_qdp QOP_DN_dw_extract_L_to_qdp
#define QOP_dw_extract_L_to_raw QOP_DN_dw_extract_L_to_raw
#define QOP_dw_force_multi QOP_DN_dw_force_multi
#define QOP_dw_force QOP_DN_dw_force
#define QOP_dw_invert_multi_qdp QOP_DN_dw_invert_multi_qdp
#define QOP_dw_invert_multi QOP_DN_dw_invert_multi
#define QOP_dw_invert_qdp QOP_DN_dw_invert_qdp
#define QOP_dw_invert QOP_DN_dw_invert
#define QOP_dw_load_L_from_G QOP_DN_dw_load_L_from_G
#define QOP_dw_load_L_from_qdp QOP_DN_dw_load_L_from_qdp
#define QOP_dw_load_L_from_raw QOP_DN_dw_load_L_from_raw
#define QOP_elem QOP_DN_elem
#define QOP_extract_D_to_qdp QOP_DN_extract_D_to_qdp
#define QOP_extract_D_to_raw QOP_DN_extract_D_to_raw
#define QOP_extract_F_to_qdp QOP_DN_extract_F_to_qdp
#define QOP_extract_F_to_raw QOP_DN_extract_F_to_raw
#define QOP_extract_G_to_qdp QOP_DN_extract_G_to_qdp
#define QOP_extract_G_to_raw QOP_DN_extract_G_to_raw
#define QOP_extract_V_to_qdp QOP_DN_extract_V_to_qdp
#define QOP_extract_V_to_raw QOP_DN_extract_V_to_raw
#define QOP_FermionLinksAsqtad QOP_DN_FermionLinksAsqtad
#define QOP_FermionLinksDW QOP_DN_FermionLinksDW
#define QOP_FermionLinksHisq QOP_DN_FermionLinksHisq
#define QOP_FermionLinksWilson QOP_DN_FermionLinksWilson
#define QOP_Force QOP_DN_Force
#define QOP_gauge_deriv_multi_qdp QOP_DN_gauge_deriv_multi_qdp
#define QOP_GaugeField QOP_DN_GaugeField
#define QOP_gauge_force_multi_qdp QOP_DN_gauge_force_multi_qdp
#define QOP_get_asqtad_deps_links_from_hisq QOP_DN_get_asqtad_deps_links_from_hisq
#define QOP_get_asqtad_links_from_hisq QOP_DN_get_asqtad_links_from_hisq
#define QOP_get QOP_DN_get
#define QOP_hisq_create_L_from_G QOP_DN_hisq_create_L_from_G
#define QOP_hisq_deriv_multi_qdp QOP_DN_hisq_deriv_multi_qdp
#define QOP_hisq_destroy_L QOP_DN_hisq_destroy_L
#define QOP_hisq_force_multi_qdp QOP_DN_hisq_force_multi_qdp
#define QOP_hisq_force_multi QOP_DN_hisq_force_multi
#define QOP_hisq_force_multi_reunit QOP_DN_hisq_force_multi_reunit
#define QOP_projectU_deriv_qdp QOP_DN_projectU_deriv_qdp
#define QOP_projectU_qdp QOP_DN_projectU_qdp
#define QOP_qla_type_D QOP_DN_qla_type_D
#define QOP_qla_type_M QOP_DN_qla_type_M
#define QOP_qla_type_ QOP_DN_qla_type_
#define QOP_qla_type_V QOP_DN_qla_type_V
#define QOP_raw_get_D QOP_DN_raw_get_D
#define QOP_raw_get_G QOP_DN_raw_get_G
#define QOP_raw_get_M QOP_DN_raw_get_M
#define QOP_raw_get_V QOP_DN_raw_get_V
#define QOP_raw_set_D QOP_DN_raw_set_D
#define QOP_raw_set_F QOP_DN_raw_set_F
#define QOP_raw_set_G QOP_DN_raw_set_G
#define QOP_raw_set_V QOP_DN_raw_set_V
#define QOP_raw_size_D QOP_DN_raw_size_D
#define QOP_raw_size_F QOP_DN_raw_size_F
#define QOP_raw_size_G QOP_DN_raw_size_G
#define QOP_raw_size QOP_DN_raw_size
#define QOP_raw_size_V QOP_DN_raw_size_V
#define QOP_rephase_G_qdp QOP_DN_rephase_G_qdp
#define QOP_rephase_G QOP_DN_rephase_G
#define QOP_set QOP_DN_set
#define QOP_smear_fat7l_qdp QOP_DN_smear_fat7l_qdp
#define QOP_staples_deriv QOP_DN_staples_deriv
#define QOP_staples QOP_DN_staples
#define QOP_su3reunit QOP_DN_su3reunit
#define QOP_symanzik_1loop_gauge_action_qdp QOP_DN_symanzik_1loop_gauge_action_qdp
#define QOP_symanzik_1loop_gauge_action QOP_DN_symanzik_1loop_gauge_action
#define QOP_symanzik_1loop_gauge_deriv_qdp QOP_DN_symanzik_1loop_gauge_deriv_qdp
#define QOP_symanzik_1loop_gauge_force_qdp QOP_DN_symanzik_1loop_gauge_force_qdp
#define QOP_symanzik_1loop_gauge_force QOP_DN_symanzik_1loop_gauge_force
#define QOP_symanzik_1loop_gauge_heatbath_qdp QOP_DN_symanzik_1loop_gauge_heatbath_qdp
#define QOP_symanzik_1loop_gauge_staple_qdp QOP_DN_symanzik_1loop_gauge_staple_qdp
#define QOP_u3reunit QOP_DN_u3reunit
#define QOP_wilson_convert_L_from_G QOP_DN_wilson_convert_L_from_G
#define QOP_wilson_convert_L_from_qdp QOP_DN_wilson_convert_L_from_qdp
#define QOP_wilson_convert_L_from_raw(...) QOP_DN_wilson_convert_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_wilson_convert_L_to_G QOP_DN_wilson_convert_L_to_G
#define QOP_wilson_convert_L_to_qdp QOP_DN_wilson_convert_L_to_qdp
#define QOP_wilson_convert_L_to_raw QOP_DN_wilson_convert_L_to_raw
#define QOP_wilson_create_L_from_G QOP_DN_wilson_create_L_from_G
#define QOP_wilson_create_L_from_qdp QOP_DN_wilson_create_L_from_qdp
#define QOP_wilson_create_L_from_raw(...) QOP_DN_wilson_create_L_from_raw(QOP_Nc, __VA_ARGS__)
#define QOP_wilson_deriv_multi_qdp QOP_DN_wilson_deriv_multi_qdp
#define QOP_wilson_deriv_prec_multi_qdp QOP_DN_wilson_deriv_prec_multi_qdp
#define QOP_wilson_destroy_L QOP_DN_wilson_destroy_L
#define QOP_wilson_diaginv_qdp QOP_DN_wilson_diaginv_qdp
#define QOP_wilson_diaginv QOP_DN_wilson_diaginv
#define QOP_wilson_dslash_qdp QOP_DN_wilson_dslash_qdp
#define QOP_wilson_dslash QOP_DN_wilson_dslash
#define QOP_wilson_extract_L_to_qdp QOP_DN_wilson_extract_L_to_qdp
#define QOP_wilson_extract_L_to_raw QOP_DN_wilson_extract_L_to_raw
#define QOP_wilson_force_multi_qdp QOP_DN_wilson_force_multi_qdp
#define QOP_wilson_force_prec_multi_qdp QOP_DN_wilson_force_prec_multi_qdp
#define QOP_wilson_ifla_dslash_qdp QOP_DN_wilson_ifla_dslash_qdp
#define QOP_wilson_ifla_dslash QOP_DN_wilson_ifla_dslash
#define QOP_wilson_ifla_invert QOP_DN_wilson_ifla_invert
#define QOP_wilson_invert_multi_qdp QOP_DN_wilson_invert_multi_qdp
#define QOP_wilson_invert_multi QOP_DN_wilson_invert_multi
#define QOP_wilson_invert_ne_qdp QOP_DN_wilson_invert_ne_qdp
#define QOP_wilson_invert_qdp QOP_DN_wilson_invert_qdp
#define QOP_wilson_invert QOP_DN_wilson_invert
#define QOP_wilson_load_L_from_G QOP_DN_wilson_load_L_from_G
#define QOP_wilson_load_L_from_qdp QOP_DN_wilson_load_L_from_qdp
#define QOP_wilson_load_L_from_raw QOP_DN_wilson_load_L_from_raw
#define QOP_wilsonMgSetLinks QOP_DN_wilsonMgSetLinks
#define QOP_wilsonMgSolve QOP_DN_wilsonMgSolve

#endif // _QOP_DN__PC_GENERIC_H
